name: skima
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  google_fonts: ^2.0.0
  flutter_svg: ^0.21.0+1
  transformer_page_view: ^0.1.6
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
